CREATE TABLE "TB_USER" (
  "ID" INTEGER NOT NULL,
  "USER_ID" TEXT NOT NULL UNIQUE,
  "PWD" TEXT NOT NULL,
  "EMAIL" TEXT NOT NULL UNIQUE,
  "NAMES" TEXT NOT NULL,
  "ENAMES" TEXT NOT NULL,
  "EMNO" TEXT,
  "AUTH" TEXT,
  "USE_YN" TEXT,
  PRIMARY KEY("ID" AUTOINCREMENT)
)
