SELECT A.ID,
  A.USER_ID,
  A.PWD,
  A.EMAIL,
  A.NAMES,
  A.ENAMES,
  A.USE_YN,
  GROUP_CONCAT(B.AUTH, ',') AS AUTH
FROM TB_USER A,
  TB_AUTH B
WHERE B.TARGET_TYPE = 'USER'
  AND B.TARGET_ID = A.USER_ID
GROUP BY A.ID,
  A.USER_ID,
  A.PWD,
  A.EMAIL,
  A.NAMES,
  A.ENAMES,
  A.USE_YN
ORDER BY A.NAMES
