DROP TABLE IF EXISTS TB_USER;
CREATE TABLE "TB_USER" (
  "ID" INTEGER NOT NULL,
  "USER_ID" TEXT NOT NULL UNIQUE,
  "PWD" TEXT NOT NULL,
  "EMAIL" TEXT NOT NULL UNIQUE,
  "NAMES" TEXT NOT NULL,
  "ENAMES" TEXT,
  "EMNO" TEXT,
  "AUTH" TEXT,
  "USE_YN" TEXT DEFAULT 'Y',
  PRIMARY KEY("ID" AUTOINCREMENT)
);
DROP TABLE IF EXISTS TB_MENU;
CREATE TABLE "TB_MENU" (
  "ID" INTEGER NOT NULL UNIQUE,
  "MENU_ID" TEXT NOT NULL UNIQUE,
  "PMENU_ID" TEXT NOT NULL,
  "MENU_NAME" TEXT NOT NULL,
  "MENU_PATH" TEXT,
  "ICON" TEXT,
  "SEPARATOR_YN" TEXT,
  "AUTH" TEXT NOT NULL,
  "SORT_NO" NUMBER,
  "USE_YN" TEXT DEFAULT 'Y',
  PRIMARY KEY("ID" AUTOINCREMENT)
);
